# Generated by Django 4.2.2 on 2023-06-08 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commissioner', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='team_profile_pictures/person.svg', upload_to='team_profile_pictures/')),
                ('draft_order', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=255)),
                ('team_one_accepted', models.BooleanField(default=False)),
                ('team_two_accepted', models.BooleanField(default=False)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_team_one', to='base.team')),
                ('team_one_sends', models.ManyToManyField(related_name='trade_team_one_sends', to='base.pick')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_team_two', to='base.team')),
                ('team_two_sends', models.ManyToManyField(related_name='trade_team_two_sends', to='base.pick')),
            ],
        ),
        migrations.AddField(
            model_name='pick',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_picks', to='base.team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='original_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_picks', to='base.team'),
        ),
    ]
