# Generated by Django 4.2.2 on 2023-06-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_trade_current_proposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('PROPOSED', 'Proposed'), ('COUNTERED', 'Countered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=255),
        ),
    ]
