# Generated by Django 4.2.2 on 2023-06-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_trade_team_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('PROPOSED', 'Proposed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=255),
        ),
    ]
