# Generated by Django 4.2.2 on 2023-06-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='extra_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
