# Generated by Django 4.2.2 on 2023-06-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_trade_extra_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='new_trade',
            field=models.BooleanField(default=False),
        ),
    ]
