# Generated by Django 4.2.2 on 2023-06-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_team_new_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='new_trade',
        ),
        migrations.AddField(
            model_name='trade',
            name='team_one_trade_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='team_two_trade_seen',
            field=models.BooleanField(default=False),
        ),
    ]
