# Generated by Django 4.2.2 on 2023-06-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_team_new_trade_trade_team_one_trade_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='team_one_trade_seen',
            new_name='team_one_viewed',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='team_two_trade_seen',
            new_name='team_two_viewed',
        ),
    ]
